### ISSUE TITLE
I don't know how to start

### ISSUE THREAD

**Issue by firolololo** [kacky24/stylenet#1]
I am sorry to bother you, but i am a recruit in caption. I am very interested in this paper and would be very appreciate if you show more about your data fold. Thanks.

**Comment by kacky24** [comment]
Data loader and preprocessing  depend on the data, flickrstyle10k dataset. 
However, it is not open, so I can't share the dataset.
I asked authors to share it when I implemented this.
If you use another data, you may have to modify data loader. 

In my data, a line in factual_train.txt includes image name, id of the caption for the same image and caption.
ex) 111111.jpg#0    this is a caption.
a line in funny_train.txt includes only caption with humorous style. 

In addition, my code is not completed.
It can generate sentences, but they are not related to images.
I consider image features are not transmitted properly because of my implementation mistakes.
However, now I am busy so don't have enough time to find bug and modify it.
I am sorry for it.

**Comment by firolololo** [comment]
Thanks a lot for your reply~
